apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop-dev
  region: us-east-1

managedNodeGroups:
  - name: roboshop-dev-ng
    instanceTypes: ["t3.medium", "t3.large"] #we can give multiple instance types based on the workload and when we use spoton instance aws will give which ever possible instances that it have available.
    desiredCapacity: 2 # by default aws will choose 3 for desired capacity
    spot: true
